Add theme options label customization
Danktuary/vuepress-theme-yuu pull request #19
Opened 2020-05-07 13:48 UTC by System-Glitch

Related to #18 

This PR adds two new configuration entries:
- `optionLabelDarkTheme`: the label shown in the Theme settings for the dark theme toggle
- `optionLabelIgnore`: the label shown in the Theme settings for the ignore forced theme toggle

2020-05-07 23:29 UTC, Danktuary commented
Hey, thanks for the PR! Would you mind renaming the options to `yuu.labels.darkTheme` and `yuu.labels.forcedThemes`?

2020-05-11 12:09 UTC, System-Glitch commented
@Danktuary I made the change. Tell me if you need anything else.

2020-05-11 22:32 UTC, Danktuary commented
Commit it and I'll merge 😄

2020-05-12 09:08 UTC, System-Glitch commented
@Danktuary e7d61ef

2020-05-12 10:27 UTC, Danktuary commented
What about my other comment?

2020-05-12 10:50 UTC, System-Glitch commented
What other comment? I changed the options names.

2020-05-12 11:17 UTC, Danktuary commented
Oh, my fault 🤦🏻‍♂️ I forgot to submit the review

2020-05-12 11:18 UTC, Danktuary requested changes

2020-05-12 11:18 UTC, Danktuary commented on mixins/yuuConfig.js
> +			labels: yuu.labels || {
I think there should be a labels variable above the `this.yuu = { ... }` definition, like so:
```js
const { labels = {} } = yuu;
```

And then the `labels` property as:
```js
labels: { darkTheme: labels.darkTheme || 'Enable Dark Theme?', ... }
```

Because otherwise, if you supplied just one label, the other wouldn't display.

2020-05-12 12:34 UTC, System-Glitch commented on mixins/yuuConfig.js
> +			labels: yuu.labels || {
I also changed the lifecycle hook from `mounted` to `beforeMount` to avoid an error on the first render of `ThemeOptions.vue`.

2020-05-14 01:23 UTC, merged